In [16]:
import tensorflow as tf
from keras.preprocessing.text import one_hot
from keras.layers import Embedding
from keras_preprocessing.sequence import pad_sequences
from keras.models import Sequential
import numpy as np

In [17]:
sentences = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'i am a good boy',
    'i love apple',
    'i am a ml intern',
    'you are beautiful'
    ]
sentences

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i love apple',
 'i am a ml intern',
 'you are beautiful']

In [18]:
voc_size = 100000

In [19]:
one_hot_representation = [one_hot(sentences, voc_size) for sentences in sentences]

In [20]:
print(one_hot_representation)

[[97114, 37222, 39970, 12678], [97114, 37222, 39970, 59483], [97114, 16970, 39970, 15055], [35458, 83839, 64307, 39822, 89733], [35458, 65791, 53800], [35458, 83839, 64307, 75847, 15341], [40795, 48246, 19243]]


In [21]:
sentence_length = 8
embeded_docs = pad_sequences(one_hot_representation, padding='pre',
                             maxlen=sentence_length)
print(embeded_docs)

[[    0     0     0     0 97114 37222 39970 12678]
 [    0     0     0     0 97114 37222 39970 59483]
 [    0     0     0     0 97114 16970 39970 15055]
 [    0     0     0 35458 83839 64307 39822 89733]
 [    0     0     0     0     0 35458 65791 53800]
 [    0     0     0 35458 83839 64307 75847 15341]
 [    0     0     0     0     0 40795 48246 19243]]


In [27]:
model =  Sequential()
model.add(Embedding(voc_size,10, input_length=sentence_length))
model.compile(optimizer=tf.keras.optimizers.legacy.Adam(),metrics= ["mse"])
# model.compile('adam', 'mse')

In [28]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 8, 10)             1000000   
                                                                 
Total params: 1,000,000
Trainable params: 1,000,000
Non-trainable params: 0
_________________________________________________________________


In [29]:
model.predict(embeded_docs)

1/1 [==============================] - 0s 86ms/step


2024-03-31 17:15:06.689525: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


array([[[ 0.03511343,  0.02778416, -0.01272653, -0.02718158,
          0.01934588,  0.0063652 ,  0.03381033, -0.01916932,
          0.01782007,  0.01241852],
        [ 0.03511343,  0.02778416, -0.01272653, -0.02718158,
          0.01934588,  0.0063652 ,  0.03381033, -0.01916932,
          0.01782007,  0.01241852],
        [ 0.03511343,  0.02778416, -0.01272653, -0.02718158,
          0.01934588,  0.0063652 ,  0.03381033, -0.01916932,
          0.01782007,  0.01241852],
        [ 0.03511343,  0.02778416, -0.01272653, -0.02718158,
          0.01934588,  0.0063652 ,  0.03381033, -0.01916932,
          0.01782007,  0.01241852],
        [-0.01778485,  0.03541142,  0.02480778, -0.02050467,
          0.02583734, -0.0370796 ,  0.032518  , -0.03077892,
         -0.03437697, -0.04718144],
        [ 0.00759319, -0.02997327,  0.04802445,  0.03925395,
          0.00892501, -0.03038192, -0.04548783,  0.02109602,
         -0.00925137,  0.03817319],
        [-0.034159  ,  0.04074098, -0.01250989,  0.0

In [30]:
# this is giving us 10 dimension embeded vector for a sentence in 0th index of 
# our array
print(model.predict(embeded_docs)[0])

1/1 [==============================] - 0s 17ms/step
[[ 0.03511343  0.02778416 -0.01272653 -0.02718158  0.01934588  0.0063652
   0.03381033 -0.01916932  0.01782007  0.01241852]
 [ 0.03511343  0.02778416 -0.01272653 -0.02718158  0.01934588  0.0063652
   0.03381033 -0.01916932  0.01782007  0.01241852]
 [ 0.03511343  0.02778416 -0.01272653 -0.02718158  0.01934588  0.0063652
   0.03381033 -0.01916932  0.01782007  0.01241852]
 [ 0.03511343  0.02778416 -0.01272653 -0.02718158  0.01934588  0.0063652
   0.03381033 -0.01916932  0.01782007  0.01241852]
 [-0.01778485  0.03541142  0.02480778 -0.02050467  0.02583734 -0.0370796
   0.032518   -0.03077892 -0.03437697 -0.04718144]
 [ 0.00759319 -0.02997327  0.04802445  0.03925395  0.00892501 -0.03038192
  -0.04548783  0.02109602 -0.00925137  0.03817319]
 [-0.034159    0.04074098 -0.01250989  0.01033216 -0.0036728   0.01621347
   0.01590386  0.03297651  0.04338661  0.00630661]
 [ 0.02673687 -0.03798567  0.00516691  0.03794754  0.04018065  0.01419571
  -0